workspace = { members = ["src/tensors"] }
[package]
name = "LAfNA"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tensors = {path = "src/tensors/"}